# Configuration du robot

motor_pin:
 motor_right_1: 16
 motor_right_2: 18
 motor_left_3: 13
 motor_left_4: 15

screen:
 width: 1920
 height: 1080
 fullscreen: True
 color_background_r: 30
 color_background_g: 30
 color_background_b: 30
 title_caption: 'Vikki'
 eye_padding: 700
 eye_speed: 10
 eye_color_r: 40
 eye_color_g: 16
 eye_color_b: 180